; Surcharges dev-friendly. A durcir pour un vrai environnement de prod
; (opcache.validate_timestamps=0, display_errors=Off, etc.).

memory_limit = 256M
upload_max_filesize = 32M
post_max_size = 32M

date.timezone = Europe/Paris

opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
